# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MysqlMcpServer < Formula
  desc "MySQL MCP Server - Model Context Protocol server for MySQL databases"
  homepage "https://github.com/askdba/mysql-mcp-server"
  version "1.7.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/askdba/mysql-mcp-server/releases/download/v1.7.1/mysql-mcp-server_1.7.1_darwin_amd64.tar.gz"
      sha256 "b6ff546288a0f9dae85f00dce1eca54d218281e80129b61cc0a07678289b59e3"

      define_method(:install) do
        bin.install "mysql-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/askdba/mysql-mcp-server/releases/download/v1.7.1/mysql-mcp-server_1.7.1_darwin_arm64.tar.gz"
      sha256 "4ce16da0a837f59b2f354639aee7073ccbeb9d73f0503850cf9417e4a9a6591c"

      define_method(:install) do
        bin.install "mysql-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/askdba/mysql-mcp-server/releases/download/v1.7.1/mysql-mcp-server_1.7.1_linux_amd64.tar.gz"
      sha256 "db84afeac9db1e1e8f46835d80bc69598efa8143a9e7862bfea9d49813cc60b5"
      define_method(:install) do
        bin.install "mysql-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/askdba/mysql-mcp-server/releases/download/v1.7.1/mysql-mcp-server_1.7.1_linux_arm64.tar.gz"
      sha256 "ff9a0c84e8f9d0f7c3440d1369b8c4e0120ebb6c477b3331416c9b3789cd04b6"
      define_method(:install) do
        bin.install "mysql-mcp-server"
      end
    end
  end

  def caveats
    <<~EOS
      To use mysql-mcp-server with Claude Desktop, add to your config:

        {
          "mcpServers": {
            "mysql": {
              "command": "#{HOMEBREW_PREFIX}/bin/mysql-mcp-server",
              "env": {
                "MYSQL_DSN": "user:password@tcp(localhost:3306)/database"
              }
            }
          }
        }

      Config location:
        macOS: ~/Library/Application Support/Claude/claude_desktop_config.json
        Linux: ~/.config/Claude/claude_desktop_config.json

      REST API: set MYSQL_MCP_HTTP=1 (and MYSQL_DSN). The token dashboard at http://localhost:9306/status is enabled by default; set MYSQL_MCP_TOKEN_CARD=0 to disable.
    EOS
  end

  test do
    assert_match "mysql-mcp-server", shell_output("#{bin}/mysql-mcp-server --version")
  end
end
