# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MysqlMcpServer < Formula
  desc "MySQL MCP Server - Model Context Protocol server for MySQL databases"
  homepage "https://github.com/askdba/mysql-mcp-server"
  version "1.7.1-rc.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/askdba/mysql-mcp-server/releases/download/v1.7.1-rc.2/mysql-mcp-server_1.7.1-rc.2_darwin_amd64.tar.gz"
      sha256 "0ee3c4663ba44df09edbee5dbbc7fa8e0e0fb5091136d93ba4bfc8003080d70f"

      define_method(:install) do
        bin.install "mysql-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/askdba/mysql-mcp-server/releases/download/v1.7.1-rc.2/mysql-mcp-server_1.7.1-rc.2_darwin_arm64.tar.gz"
      sha256 "58f3bfe482e65afe4c81c52be0393f8e1409ad8fee86cf8fe3b7c58f9903136a"

      define_method(:install) do
        bin.install "mysql-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/askdba/mysql-mcp-server/releases/download/v1.7.1-rc.2/mysql-mcp-server_1.7.1-rc.2_linux_amd64.tar.gz"
      sha256 "05a16481fe2d41f550e6f9316a568c4b89731a732bacddd08067af1079979c27"
      define_method(:install) do
        bin.install "mysql-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/askdba/mysql-mcp-server/releases/download/v1.7.1-rc.2/mysql-mcp-server_1.7.1-rc.2_linux_arm64.tar.gz"
      sha256 "0be8bc9d140a97d37e116db7b2f8755277bead1de332b83aa9ef50ddfc68df41"
      define_method(:install) do
        bin.install "mysql-mcp-server"
      end
    end
  end

  def caveats
    <<~EOS
      To use mysql-mcp-server with Claude Desktop, add to your config:

        {
          "mcpServers": {
            "mysql": {
              "command": "#{HOMEBREW_PREFIX}/bin/mysql-mcp-server",
              "env": {
                "MYSQL_DSN": "user:password@tcp(localhost:3306)/database"
              }
            }
          }
        }

      Config location:
        macOS: ~/Library/Application Support/Claude/claude_desktop_config.json
        Linux: ~/.config/Claude/claude_desktop_config.json

      REST API: set MYSQL_MCP_HTTP=1 (and MYSQL_DSN). The token dashboard at http://localhost:9306/status is enabled by default; set MYSQL_MCP_TOKEN_CARD=0 to disable.
    EOS
  end

  test do
    assert_match "mysql-mcp-server", shell_output("#{bin}/mysql-mcp-server --version")
  end
end
