# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MysqlMcpServer < Formula
  desc "MySQL MCP Server - Model Context Protocol server for MySQL databases"
  homepage "https://github.com/askdba/mysql-mcp-server"
  version "1.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/askdba/mysql-mcp-server/releases/download/v1.5.0/mysql-mcp-server_1.5.0_darwin_amd64.tar.gz"
      sha256 "4eee5a6dc9f4b97a6ae7016a7c054fdfea7917834ae1a046bedf1eeaaa1d841c"

      def install
        bin.install "mysql-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/askdba/mysql-mcp-server/releases/download/v1.5.0/mysql-mcp-server_1.5.0_darwin_arm64.tar.gz"
      sha256 "58c8e3037a3cfc3b975f1e96909a0c97ce6917208229896d33dfda52b9fe7ed3"

      def install
        bin.install "mysql-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/askdba/mysql-mcp-server/releases/download/v1.5.0/mysql-mcp-server_1.5.0_linux_amd64.tar.gz"
      sha256 "8b8c12881b2c2b2710d3d5cacc1fda933a4b58bc383f5c59c517a7d1a4999a45"
      def install
        bin.install "mysql-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/askdba/mysql-mcp-server/releases/download/v1.5.0/mysql-mcp-server_1.5.0_linux_arm64.tar.gz"
      sha256 "b192890655065ce39bfaf5ecb4972d4ff1a84825f417f334ad3f3aa9a53650b6"
      def install
        bin.install "mysql-mcp-server"
      end
    end
  end

  def caveats
    <<~EOS
      To use mysql-mcp-server with Claude Desktop, add to your config:

        {
          "mcpServers": {
            "mysql": {
              "command": "#{HOMEBREW_PREFIX}/bin/mysql-mcp-server",
              "env": {
                "MYSQL_DSN": "user:password@tcp(localhost:3306)/database"
              }
            }
          }
        }

      Config location:
        macOS: ~/Library/Application Support/Claude/claude_desktop_config.json
        Linux: ~/.config/Claude/claude_desktop_config.json
    EOS
  end

  test do
    assert_match "mysql-mcp-server", shell_output("#{bin}/mysql-mcp-server --version")
  end
end
